### ISSUE TITLE
HTTP connection refused for encrypted ES node

### ISSUE THREAD

**Issue by ngandrew** [olivere/elastic#1163]
### Which version of Elastic are you using?

[X] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Sniffing correctly returns `https` scheme to be used by `elastic.Client` for cluster with TLS enabled on HTTP layer.

### Please describe the actual behavior
Sniffing incorrectly changes the scheme to `http` for `elastic.Client` for cluster with TLS enabled on HTTP layer.

This is the error I get:
```
health check timeout: Head http://10.0.22.70:9200: dial tcp 10.0.22.70:9200: connect: connection refused: no Elasticsearch node available
```

It seems that I have a similar issue as [this issue](https://github.com/olivere/elastic/issues/738). In that issue, you mention that in the following `curl` request, the `http` should be `https` but I do not know how to make that so. In addition, I am not running elasticsearch in any sort of container / special environment with no special elasticsearch plugins (other than xpack I guess).

```
$ curl "https://10.0.22.70:9200/_nodes/http?pretty=true" -k
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "qQ-RqzfdQwexkmdzudgiHA" : {
      "name" : "es1",
      "transport_address" : "10.0.22.70:9300",
      "host" : "10.0.22.70",
      "ip" : "10.0.22.70",
      "version" : "7.2.0",
      "build_flavor" : "default",
      "build_type" : "rpm",
      "build_hash" : "508c38a",
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "attributes" : {
        "ml.machine_memory" : "16657338368",
        "xpack.installed" : "true",
        "ml.max_open_jobs" : "20"
      },
      "http" : {
        "bound_address" : [
          "[::]:9200"
        ],
        "publish_address" : "10.0.22.70:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

### Any steps to reproduce the behavior?
My client is started like this:
```
httpClient := &http.Client{
	Transport: &http.Transport{
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
		},
	},
}
client, err = elastic.NewClient(
	elastic.SetHttpClient(httpClient),
	elastic.SetURL("https://10.0.22.70:9200"),
	elastic.SetScheme("https"),
	// elastic.SetSniff(false),
)
```

For reference, this is my `elasticsearch.yml`:
```
bootstrap.memory_lock: true
cluster.initial_master_nodes: es1
cluster.name: elasticsearch
http.port: 9200
index.store.type: mmapfs
indices.memory.index_buffer_size: 30%
network.host: 0.0.0.0
node.data: true
node.master: true
node.name: es1
script.allowed_types: inline
search.max_open_scroll_context: 10000
thread_pool.write.queue_size: 1530
xpack.watcher.enabled: false

################################### Encryption  ##############################

# client encryption
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.verification_mode: none
xpack.security.http.ssl.key:  /etc/elasticsearch/XXX.key
xpack.security.http.ssl.certificate: /etc/elasticsearch/XXX.cert
xpack.security.http.ssl.certificate_authorities: [ "/etc/elasticsearch/ca.cert" ]


#################################### Paths ####################################

# Path to directory containing configuration (this file and logging.yml):


path.data: /var/lib/elasticsearch

path.logs: /var/log/elasticsearch


action.auto_create_index: false
```

**Comment by ngandrew** [comment]
After doing some more digging, the sniffing does not seem to be the only issue. While the sniffing is changing the scheme over to `http` after a while, the initial `https` connection is having issues, with error message:
```
health check timeout: Head https://10.0.22.70:9200: dial tcp 10.0.22.70:9200: connect: connection refused: no Elasticsearch node available
```
In addition, in the elasticsearch log file, I am seeing this error over and over again (`10.0.22.71` is where the client is running):
```
[2019-08-09T00:00:02,257][WARN ][o.e.h.AbstractHttpServerTransport] [es1] caught exception while handling client http traffic, closing connection Netty4HttpChannel{localAddress=0.0.0.0/0.0.0.0:9200, remoteAddress=/0:0:0:0:0:0:0:1:39486}
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f5f636c75737465722f6865616c746820485454502f312e310d0a486f73743a206c6f63616c686f73743a393230300d0a557365722d4167656e743a20476f2d687474702d636c69656e742f312e310d0a4163636570742d456e636f64696e673a20677a69700d0a0d0a
"/var/log/elasticsearch/elasticsearch.log" 6600L, 1005240C                                                                                                                                                              22,1-8        Top
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1206) ~[netty-handler-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274) ~[netty-handler-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.35.Final.jar:4.1.35.Final]
        ... 16 more
[2019-08-09T00:05:50,030][WARN ][o.e.h.AbstractHttpServerTransport] [es1] caught exception while handling client http traffic, closing connection Netty4HttpChannel{localAddress=0.0.0.0/0.0.0.0:9200, remoteAddress=/10.0.22.71:43154}
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f5f636c75737465722f6865616c746820485454502f312e310d0a486f73743a2031302e302e32322e37303a393230300d0a4163636570742d456e636f64696e673a206964656e746974790d0a636f6e6e656374696f6e3a206b6565702d616c6976650d0a636f6e74656e742d747970653a206170706c69636174696f6e2f6a736f6e0d0a0d0a
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[netty-codec-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.35.Final.jar:4.1.35.Final]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f5f636c75737465722f6865616c746820485454502f312e310d0a486f73743a2031302e302e32322e37303a393230300d0a4163636570742d456e636f64696e673a206964656e746974790d0a636f6e6e656374696f6e3a206b6565702d616c6976650d0a636f6e74656e742d747970653a206170706c69636174696f6e2f6a736f6e0d0a0d0a
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1206) ~[netty-handler-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274) ~[netty-handler-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.35.Final.jar:4.1.35.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.35.Final.jar:4.1.35.Final]
        ... 16 more
```

**Comment by ngandrew** [comment]
I currently cannot consistently reproduce this error anymore as I have two similar systems providing different results. I will reopen this issue once I can further narrow down the issue. I don't want to unnecessarily waste anyone's time for now, so I will close the issue for the time being.
