### ISSUE TITLE
SearchContextMissing In ES 

### ISSUE THREAD

**Issue by Kartikkh** [olivere/elastic#1196]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[X] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I was previously using Elastic 6.2 version (single machine) with the GO elastic module of elastic 5.X
And everything was working fine till then. 
As I have upgraded the Elastic search version to 6.7 (now 4 data node and 1 master node every on a different machine in a cluster) with same elastic 5.X. I am getting following errors with elastic search and not able to serve the Result using ES query
My code works fine for 2-3 hours first and then everything collapse. 

*ES error* 
```[DEBUG][o.e.a.s.TransportSearchScrollAction]
[1344693] Failed to execute query phase
org.elasticsearch.transport.RemoteTransportException: [elasticsearch-6-7-XXX-XX-XX-XX][172.XX.XX.XX:9300][indices:data/read/search[phase/query/scroll]]
Caused by: org.elasticsearch.search.SearchContextMissingException: No search context found for id [1344693]
        at org.elasticsearch.search.SearchService.getExecutor(SearchService.java:496) ~[elasticsearch-6.7.2.jar:6.7.2]
        at org.elasticsearch.search.SearchService.runAsync(SearchService.java:373) ~[elasticsearch-6.7.2.jar:6.7.2]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:435) ~[elasticsearch-6.7.2.jar:6.7.2]
        at org.elasticsearch.action.search.SearchTransportService$8.messageReceived(SearchTransportService.java:376) ~[elasticsearch-6.7.2.jar:6.7.2]
        at org.elasticsearch.action.search.SearchTransportService$8.messageReceived(SearchTransportService.java:373) ~[elasticsearch-6.7.2.jar:6.7.2]
      at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.7.2.ja
r:6.7.2]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1087) ~[elasticsearch-6.7.2.jar:6.7.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.7.2.jar:6.7.2]
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192) ~[elasticsearch-6.7.2.jar
:6.7.2]
        at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1046) [elasticsearch-6.7.2.jar:6.7.2]
        at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:932) [elasticsearch-6.7.2.jar:6.7.2]
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:763) [elasticsearch-6.7.2.jar:6.7.2]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53) [transport-netty4-
client-6.7.2.jar:6.7.2]
````

This clearly says that there is a problem with the ES scroll. 
So I thought maybe there is a version compatible issue with the current ES 6.7 and ES go module 5.X

So I have updated the ES go module to 6.X.
Now I have ES version of 6.7 with ES Go lib version to 6.X.

My code and query related is 
```

q := elastic.NewTermQuery("ABC", 1)
	bq = elastic.NewBoolQuery().Filter(q)
	bq = bq.MustNot(elastic.NewTermQuery("wrong", "XXX"))
        bq = bq.Must(elastic.NewTermQuery("ID", 12132))
	
query = bq 

```
    hits := make(chan json.RawMessage)
	g, ctx := errgroup.WithContext(context.Background())
	g.Go(func() error {
		defer close(hits)
		scrollService := elastic.Scroll(Index).Type(Type).Query(query).Size(250)
		for {
			results, err := scrollService.Do(context.TODO())
			if err == io.EOF {
				log.Println("In for EOF")
				return nil // all results retrieved
			}
			if err != nil {
			 // This error occurs after some time and logs the error 
			 //[Elastic Error: elastic: Error 404 (Not Found): all shards failed //[type=search_phase_execution_exception]
				log.Println("[Elastic Error:", err)
				continue
			}

			// Send the hits to the hits channel
			for _, hit := range results.Hits.Hits {
				select {
				case hits <- *hit.Source:
				case <-ctx.Done():
					return ctx.Err()
				}
			}
		}
	})

	for i := 0; i < 100; i++ {
		g.Go(func() error {
			for hit := range hits {
				err = json.Unmarshal(hit, &XXX)
				if err != nil {
                    log.println("xxx)
					continue
				}
				
				My processing is here !!!
				
				
				select {
				default:
				case <-ctx.Done():
					return ctx.Err()
				}
			}
			return nil
		})
	}

	// Check whether any goroutines failed.
	if err := g.Wait(); err != nil {
		log.Printf("Go Routine Err:%s", err.Error())
	}
```
### Any steps to reproduce the behavior?
The code works fine for 2-3 hours and after that, it throws error a lot

**Comment by olivere** [comment]
You typically get this error when the token that gets passed for the scroll operation times out. Can you check and see if you can set a longer timeout.

**Comment by Kartikkh** [comment]
@olivere  how do i set a longer timeout ?

**Comment by olivere** [comment]
See https://github.com/olivere/elastic/blob/release-branch.v7/scroll.go#L101

**Comment by Kartikkh** [comment]
> See https://github.com/olivere/elastic/blob/release-branch.v7/scroll.go#L101
@olivere 
Added KeepAlive to 10m
but still not able to remove the error

**Comment by olivere** [comment]
Everything I read about SearchContextMissingException on the internet says that you’re trying to access a „cursor“ that has expired or doesn’t exist any more in the ES cluster. I don’t know why that happens though. It may of course be a bug in the library, but it’s been in use for years, so I guess that should’ve been uncovered in the recent years. is there any chance you can reproduce the problem with a dataset? Do you delay work while scrolling sometimes?

**Comment by Kartikkh** [comment]
yes, there is a delay but that's too in microseconds.

**Comment by Kartikkh** [comment]
But the question is why this is a problem when I switch to the ES cluster having 4 data nodes. 
while this code works fine in a single elastic machine with 1 node having the same documents 
Is there any problem with scroll in version 6.7 
bcoz everything works fine in version 6.3

**Comment by olivere** [comment]
I don’t know of any issues. I think Scroll API didn’t change significantly since the 3.x to 5.x update.
