### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by wsqun** [olivere/elastic#1257]
i use v5 and v6,they all about it. 
i have to add timer to slow the bulk update
```
bulkRequest := self.ElasticClient.Bulk()
for req := range self.BulkChUpdate {
	bulkRequest = bulkRequest.Add(req)
	if bulkRequest.NumberOfActions() >= ExecuteBulkUpdateNums {
		tc := time.NewTimer(50 * time.Millisecond)
		<-tc.C
		
		bulkResponse, err := bulkRequest.Do(context.TODO())
		if err != nil {
			fmt.Println(err)
		}
		if bulkResponse == nil {
			fmt.Println("expected bulkResponse to be != nil; got nil")
		}
		break
	}
}
```
```

goroutine 11 [running]:
runtime.throw(0xb9eba7, 0x26)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0000f4e08 sp=0xc0000f4dd8 pc=0x430a42
runtime.mapiternext(0xc000148540)
	/usr/local/go/src/runtime/map.go:858 +0x579 fp=0xc0000f4e90 sp=0xc0000f4e08 pc=0x410c19
reflect.mapiternext(0xc000148540)
	/usr/local/go/src/runtime/map.go:1347 +0x2b fp=0xc0000f4ea8 sp=0xc0000f4e90 pc=0x411c2b
reflect.Value.MapKeys(0xa92540, 0xc00039e660, 0x15, 0x0, 0x40f66b, 0xc0000f5008)
	/usr/local/go/src/reflect/value.go:1214 +0x10a fp=0xc0000f4f38 sp=0xc0000f4ea8 pc=0x49308a
encoding/json.mapEncoder.encode(0xbb5438, 0xc0007880e0, 0xa92540, 0xc00039e660, 0x15, 0xa90100)
	/usr/local/go/src/encoding/json/encode.go:690 +0xff fp=0xc0000f5080 sp=0xc0000f4f38 pc=0x4fdbbf
encoding/json.mapEncoder.encode-fm(0xc0007880e0, 0xa92540, 0xc00039e660, 0x15, 0xc000390100)
	/usr/local/go/src/encoding/json/encode.go:682 +0x64 fp=0xc0000f50c0 sp=0xc0000f5080 pc=0x508f44
encoding/json.(*encodeState).reflectValue(0xc0007880e0, 0xa92540, 0xc00039e660, 0x15, 0xc000390100)
	/usr/local/go/src/encoding/json/encode.go:337 +0x82 fp=0xc0000f50f8 sp=0xc0000f50c0 pc=0x4fb0b2
encoding/json.interfaceEncoder(0xc0007880e0, 0xa8e460, 0xc0006b2490, 0x94, 0xc0006b0100)
	/usr/local/go/src/encoding/json/encode.go:619 +0xac fp=0xc0000f5140 sp=0xc0000f50f8 pc=0x4fd36c
encoding/json.mapEncoder.encode(0xbb5438, 0xc0007880e0, 0xa92540, 0xc00039e6c0, 0x15, 0xa90100)
	/usr/local/go/src/encoding/json/encode.go:706 +0x351 fp=0xc0000f5288 sp=0xc0000f5140 pc=0x4fde11
encoding/json.mapEncoder.encode-fm(0xc0007880e0, 0xa92540, 0xc00039e6c0, 0x15, 0xc000780100)
	/usr/local/go/src/encoding/json/encode.go:682 +0x64 fp=0xc0000f52c8 sp=0xc0000f5288 pc=0x508f44
encoding/json.(*encodeState).reflectValue(0xc0007880e0, 0xa92540, 0xc00039e6c0, 0x15, 0xc000780100)
	/usr/local/go/src/encoding/json/encode.go:337 +0x82 fp=0xc0000f5300 sp=0xc0000f52c8 pc=0x4fb0b2
encoding/json.(*encodeState).marshal(0xc0007880e0, 0xa92540, 0xc00039e6c0, 0xc0000f0100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:309 +0x10b fp=0xc0000f5380 sp=0xc0000f5300 pc=0x4fab5b
encoding/json.Marshal(0xa92540, 0xc00039e6c0, 0xc00039e6c0, 0x0, 0x0, 0x0, 0xb050e0)
	/usr/local/go/src/encoding/json/encode.go:161 +0x52 fp=0xc0000f53f8 sp=0xc0000f5380 pc=0x4fa2e2
gopkg.in/olivere/elastic%2ev5.easyjson1ed00e60EncodeGopkgInOlivereElasticV51(0xc0007881c0, 0x0, 0xa92540, 0xc00039e6c0, 0x0, 0xaed7e0, 0xc00039e6f0, 0x0, 0x0, 0x0, ...)
	/home/www/sy_go/pkg/mod/gopkg.in/olivere/elastic.v5@v5.0.82/bulk_update_request_easyjson.go:303 +0x646 fp=0xc0000f5450 sp=0xc0000f53f8 pc=0x7eacc6
gopkg.in/olivere/elastic%2ev5.bulkUpdateRequestCommandData.MarshalJSON(0x0, 0xa92540, 0xc00039e6c0, 0x0, 0xaed7e0, 0xc00039e6f0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/www/sy_go/pkg/mod/gopkg.in/olivere/elastic.v5@v5.0.82/bulk_update_request_easyjson.go:374 +0x61 fp=0xc0000f54c0 sp=0xc0000f5450 pc=0x7eae11
gopkg.in/olivere/elastic%2ev5.(*bulkUpdateRequestCommandData).MarshalJSON(0xc000172320, 0xb2e100, 0xc000172320, 0x7fee1025a148, 0xc000172320, 0xc000172301)
	<autogenerated>:1 +0x85 fp=0xc0000f5598 sp=0xc0000f54c0 pc=0x8ce3b5
encoding/json.marshalerEncoder(0xc000788000, 0xb2e100, 0xc000172320, 0x99, 0x100)
	/usr/local/go/src/encoding/json/encode.go:453 +0xc4 fp=0xc0000f5618 sp=0xc0000f5598 pc=0x4fba44
encoding/json.(*encodeState).reflectValue(0xc000788000, 0xb2e100, 0xc000172320, 0x99, 0x100)
	/usr/local/go/src/encoding/json/encode.go:337 +0x82 fp=0xc0000f5650 sp=0xc0000f5618 pc=0x4fb0b2
encoding/json.(*encodeState).marshal(0xc000788000, 0xb2e100, 0xc000172320, 0x100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:309 +0x10b fp=0xc0000f56d0 sp=0xc0000f5650 pc=0x4fab5b
encoding/json.Marshal(0xb2e100, 0xc000172320, 0xb2e100, 0xc000172320, 0xc00078c5a0, 0x8f, 0x0)
	/usr/local/go/src/encoding/json/encode.go:161 +0x52 fp=0xc0000f5748 sp=0xc0000f56d0 pc=0x4fa2e2
gopkg.in/olivere/elastic%2ev5.(*BulkUpdateRequest).Source(0xc0007060f0, 0xc0006b0240, 0x2, 0x2, 0x0, 0x0)
	/home/www/sy_go/pkg/mod/gopkg.in/olivere/elastic.v5@v5.0.82/bulk_update_request.go:287 +0x4a4 fp=0xc0000f5910 sp=0xc0000f5748 pc=0x7e88b4
gopkg.in/olivere/elastic%2ev5.(*BulkService).estimateSizeInBytes(0xc0000f5f10, 0xc6c300, 0xc0007060f0, 0x148)
	/home/www/sy_go/pkg/mod/gopkg.in/olivere/elastic.v5@v5.0.82/bulk.go:155 +0x31 fp=0xc0000f5950 sp=0xc0000f5910 pc=0x7e1441
gopkg.in/olivere/elastic%2ev5.(*BulkService).EstimatedSizeInBytes(0xc0000f5f10, 0x0)
	/home/www/sy_go/pkg/mod/gopkg.in/olivere/elastic.v5@v5.0.82/bulk.go:145 +0xa7 fp=0xc0000f5998 sp=0xc0000f5950 pc=0x7e1397
gopkg.in/olivere/elastic%2ev5.(*BulkService).bodyAsString(0xc0000f5f10, 0x0, 0x0, 0x0, 0x0)
	/home/www/sy_go/pkg/mod/gopkg.in/olivere/elastic.v5@v5.0.82/bulk.go:172 +0x40 fp=0xc0000f5a38 sp=0xc0000f5998 pc=0x7e14e0
gopkg.in/olivere/elastic%2ev5.(*BulkService).Do(0xc0000f5f10, 0xc725e0, 0xc000028148, 0x1, 0xc000062f10, 0x0)
	/home/www/sy_go/pkg/mod/gopkg.in/olivere/elastic.v5@v5.0.82/bulk.go:198 +0x4e fp=0xc0000f5e70 sp=0xc0000f5a38 pc=0x7e174e
tools/Uprofile/components.(*EsDataService).bulkUpdate(0xc000101260)
	/home/www/go_project/tools/Uprofile/components/Es.go:96 +0xf6 fp=0xc0000f5fd8 sp=0xc0000f5e70 pc=0x9e45e6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000f5fe0 sp=0xc0000f5fd8 pc=0x45db51
created by tools/Uprofile/components.(*EsDataService).OpenBulkUpdate
```

**Comment by olivere** [comment]
Can you share a runnable example of your code?

**Comment by olivere** [comment]
Closed for inactivity.
