### ISSUE TITLE
About  configure client to connect  to other hosts

### ISSUE THREAD

**Issue by hacpai** [olivere/elastic#130]
Hi olivere
Elastic works OK, when sending data to default url "http://localhost:9200", but when i trying to send to remote elasticsearch I'm getting error.

```go
client, err := elastic.NewClient(
		elastic.SetURL(elasticHost))
	if err != nil {
		// Handle error
		panic(err)
	}

	// Ping the Elasticsearch server to get e.g. the version number
	info, code, err := client.Ping().URL(elasticHost).Do()
	if err != nil {
		// Handle error
		panic(err)
	}
	fmt.Printf("Elasticsearch returned with code %d and version %s", code, info.Version.Number)
```

This is my test environment,

```
core@8d3c56f4-3468-4c69-9afb-6202099641f0 ~/bin $ curl 127.0.0.1:9200
{
  "status" : 200,
  "name" : "Black Tarantula",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.1",
    "build_hash" : "b88f43fc40b0bcd7f173a1f9ee2e97816de80b19",
    "build_timestamp" : "2015-07-29T09:54:16Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

core@8d3c56f4-3468-4c69-9afb-6202099641f0 ~/bin $ curl http://10.128.129.121:9200/
{
  "status" : 200,
  "name" : "Black Tarantula",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.1",
    "build_hash" : "b88f43fc40b0bcd7f173a1f9ee2e97816de80b19",
    "build_timestamp" : "2015-07-29T09:54:16Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

core@8d3c56f4-3468-4c69-9afb-6202099641f0 ~/bin $ curl http://remote_elk:9200/
{
  "status" : 200,
  "name" : "Ecstasy",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.1",
    "build_hash" : "b88f43fc40b0bcd7f173a1f9ee2e97816de80b19",
    "build_timestamp" : "2015-07-29T09:54:16Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

As you can see here is:
127.0.0.1 its localhost for 10.128.129.121 and remote_elk its some remote elk.

**Comment by olivere** [comment]
It works fine with remote hosts. We're using it in production for more than 2 years now. I suppose its `ErrNoClient`?!

I have two questions for you:

1. What is the error message you get?
2. What is the output of `curl http://<remote-ip>:9200/_nodes/http?pretty` when you run it from the server where Elastic is running?

Maybe ES is binding to an interface that is not accessible from the host that Elastic/Go is sitting on. You might look into the [sniffing process](https://github.com/olivere/elastic/wiki/Sniffing) and [Docker issues](https://github.com/olivere/elastic/wiki/Docker) (I know you're not on Docker, but it might be the same issue).

**Comment by hacpai** [comment]
I get the error message.

```
panic: no Elasticsearch node available

goroutine 1 [running]:
github.com/google/cadvisor/storage/elasticsearch.New(0xc2080a4780, 0x24, 0xb663d0, 0x8, 0xb45290, 0x5, 0x7ffdf2ef8da9, 0x24, 0x0, 0x0, ...)
    /home/tpost/go/src/github.com/google/cadvisor/storage/elasticsearch/elasticsearch.go:104 +0x1af
main.NewMemoryStorage(0x7ffdf2ef8d62, 0xd, 0xbc1890, 0x0, 0x0)
    /home/tpost/go/src/github.com/google/cadvisor/storagedriver.go:111 +0x716
main.main()
    /home/tpost/go/src/github.com/google/cadvisor/cadvisor.go:63 +0x18a

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x11ffe80)
    /home/tpost/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:839 +0x78
created by github.com/golang/glog.init·1
    /home/tpost/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:406 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
    /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 15 [IO wait]:
net.(*pollDesc).Wait(0xc208011480, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208011480, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208011420, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x7f4ea0dc8fb0, 0xc2080a0ab0)
    /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20803a2d8, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f4ea0dcb278, 0xc20803a2d8, 0xc2080fd658, 0xc20800f000, 0x1000, 0x1000, 0x9ba820, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20801fe60, 0xc20800f000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
    <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208038c60)
    /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208038c60, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080fd600)
    /usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 16 [select]:
net/http.(*persistConn).writeLoop(0xc2080fd600)
    /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:661 +0xcbc
```

2 .

```
root@ES:~/.gvm/pkgsets/go1.4.2/global/src/github.com/google/cadvisor# curl -XGET 'http://45.55.62.208:9200/_nodes/http?pretty=1'
{
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "Uy_kzkbZTT-6YE7dDWvNxQ" : {
      "name" : "Lighting Rod",
      "transport_address" : "inet[/172.17.0.1:9300]",
      "host" : "83cbfa134cfd",
      "ip" : "172.17.0.1",
      "version" : "1.7.1",
      "build" : "b88f43f",
      "http_address" : "inet[/172.17.0.1:9200]",
      "http" : {
        "bound_address" : "inet[/0:0:0:0:0:0:0:0:9200]",
        "publish_address" : "inet[/172.17.0.1:9200]",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

**Comment by olivere** [comment]
Okay. Elastic will pick up the IP address returned via HTTP nodes info:

```
"http_address" : "inet[/172.17.0.1:9200]"
```

Can you try to curl 172.17.0.1 from the machine that Elastic/Go is sitting on? I'm pretty sure it's not accessible.

Then you have two options:

1. Configure the list of HTTP endpoint URLs manually and disable sniffing.
2. Make sure Elasticsearch nodes bind to an IP address that is accessible from the client side.

For 2. you should read the Docker wiki page.

Let me know if you succeed.

**Comment by hacpai** [comment]
Thanks @olivere 

This is my new code:

```go
client, err := elastic.NewClient(
         elastic.SetSniff(false),
        elastic.SetURL(elasticHost)
    )
    if err != nil {
        // Handle error
        panic(err)
    }
```

It works.

**Comment by olivere** [comment]
Yes. That's option 1. So it's the "Docker issue". I'm sure people using cAdvisor with Elasticsearch would want both options so you should document this or somehow propose options to go for 1. or 2.

Anyway. :-)  HTH.
