### ISSUE TITLE
all shards failed [type=search_phase_execution_exception]

### ISSUE THREAD

**Issue by Julianbaozi** [olivere/elastic#1336]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[x] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
i use Postman to post json
{
	"user":"1111",
	"message":"hello",
	"location":{
		"lat":37.5,
		"lon":-120.1
	}
}
to http://localhost:8080/post

when I want to get the item I just post by
http://localhost:8080/search?lat=37.5&lon=-120
, i received

started-service
Received one request for search.
Search received: 37.500000 -120.000000 200km
2020/05/31 06:16:07 http: panic serving [::1]:41548: elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]
goroutine 22 [running]:
net/http.(*conn).serve.func1(0xc0000a61e0)
	/usr/local/go/src/net/http/server.go:1772 +0x139
panic(0x710e00, 0xc00009c4f0)
	/usr/local/go/src/runtime/panic.go:975 +0x3e3
main.handlerSearch(0x7f5ca0, 0xc0001a80e0, 0xc0000c0300)
	/home/yjl/Around/service/main.go:151 +0x128d
net/http.HandlerFunc.ServeHTTP(0x795288, 0x7f5ca0, 0xc0001a80e0, 0xc0000c0300)
	/usr/local/go/src/net/http/server.go:2012 +0x44
net/http.(*ServeMux).ServeHTTP(0xa10480, 0x7f5ca0, 0xc0001a80e0, 0xc0000c0300)
	/usr/local/go/src/net/http/server.go:2387 +0x1a5
net/http.serverHandler.ServeHTTP(0xc0001a8000, 0x7f5ca0, 0xc0001a80e0, 0xc0000c0300)
	/usr/local/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc0000a61e0, 0x7f63a0, 0xc000098140)
	/usr/local/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2933 +0x35c

By the way, the debugger is not working. there is nothing in the log file that is related to the error.

### Please describe the actual behavior
I should get the json file I just post.

### Any steps to reproduce the behavior?

[main .txt](https://github.com/olivere/elastic/files/4707839/main.txt)

I uploaded the main.go. Run it, post the json and get it.

I don't know if it has anything to do with the geo-point setting. the mapping is 
{
  "around" : {
    "mappings" : {
      "post" : {
        "properties" : {
          "location" : {
            "properties" : {
              "Lat" : {
                "type" : "double"
              },
              "lon" : {
                "type" : "double"
              }
            }
          },
          "message" : {
            "type" : "string"
          },
          "user" : {
            "type" : "string"
          }
        }
      }
    }
  }
}

**Comment by Julianbaozi** [comment]
solved by reinstalled elasticsearch
