### ISSUE TITLE
nil pointer dereference when indexing (elastic 2.0, client v3)

### ISSUE THREAD

**Issue by aspic** [olivere/elastic#155]
Hi! I just started using this library and have a pretty basic setup (locally run elastic instance). However, when I try to index a document I get the error below:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4d5fc3]

goroutine 16 [running]:
runtime.panic(0x7aaf20, 0xa64113)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
gopkg.in/olivere/elastic%2ev3.(*Client).PerformRequest(0x0, 0x811c80, 0x3, 0xc2080009b0, 0x10, 0xc208020f60, 0x7c6000, 0xc208046000, 0x0, 0x0, ...)
	/home/aspic/dev/git/words/server/src/gopkg.in/olivere/elastic.v3/client.go:884 +0xe03
gopkg.in/olivere/elastic%2ev3.(*IndexService).Do(0xc2080030e0, 0x7f928a1c2e60, 0x0, 0x0)
	/home/aspic/dev/git/words/server/src/gopkg.in/olivere/elastic.v3/index.go:263 +0x1b5
store.ElasticStore.AddTweet(0x0)
	/home/aspic/dev/git/words/server/src/store/store.go:90 +0x13f
main.main()
	/home/aspic/dev/git/words/server/src/parser/parser.go:90 +0x8c

goroutine 19 [finalizer wait]:
runtime.park(0x4132b0, 0xa68c30, 0xa66e89)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xa68c30, 0xa66e89)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 25 [runnable]:
gopkg.in/olivere/elastic%2ev3.(*Client).sniffer(0xc208060000)
	/home/aspic/dev/git/words/server/src/gopkg.in/olivere/elastic.v3/client.go:571
created by gopkg.in/olivere/elastic%2ev3.NewClient
	/home/aspic/dev/git/words/server/src/gopkg.in/olivere/elastic.v3/client.go:244 +0x738

goroutine 22 [IO wait]:
net.runtime_pollWait(0x7f928a352738, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208022d80, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208022d80, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc208022d20, 0xc208076000, 0x1000, 0x1000, 0x0, 0x7f928a351418, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc208038080, 0xc208076000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/net.go:122 +0xe7
net/http.noteEOFReader.Read(0x7f928a3527e8, 0xc208038080, 0xc20803a108, 0xc208076000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/transport.go:1203 +0x72
net/http.(*noteEOFReader).Read(0xc208040a60, 0xc208076000, 0x1000, 0x1000, 0xc20802c0e0, 0x0, 0x0)
	<autogenerated>:124 +0xca
bufio.(*Reader).fill(0xc2080046c0)
	/usr/local/go/src/pkg/bufio/bufio.go:97 +0x1b3
bufio.(*Reader).Peek(0xc2080046c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/bufio/bufio.go:132 +0x101
net/http.(*persistConn).readLoop(0xc20803a0b0)
	/usr/local/go/src/pkg/net/http/transport.go:782 +0x95
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 23 [select]:
net/http.(*persistConn).writeLoop(0xc20803a0b0)
	/usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:601 +0x957

goroutine 26 [runnable]:
gopkg.in/olivere/elastic%2ev3.(*Client).healthchecker(0xc208060000)
	/home/aspic/dev/git/words/server/src/gopkg.in/olivere/elastic.v3/client.go:747
created by gopkg.in/olivere/elastic%2ev3.NewClient
	/home/aspic/dev/git/words/server/src/gopkg.in/olivere/elastic.v3/client.go:247 +0x75d
```
During troubleshooting I've even tried to copy the test code, but no matter what the index-operation fails. Here's the index code:
```
type tweet struct {
    User     string        `json:"user"`
    Message  string        `json:"message"`
    Retweets int           `json:"retweets"`
    Image    string        `json:"image,omitempty"`
    Created  time.Time     `json:"created,omitempty"`
    Tags     []string      `json:"tags,omitempty"`
    Location string        `json:"location,omitempty"`
}

func (s ElasticStore) AddTweet() {

    tweet := tweet{User: "olivere", Message: "Take Five"}
    _, err := s.client.Index().
        Index("twitter").
        Type("test").
        Id("1").
        BodyJson(tweet).
        Do()
    if err != nil {
        // Handle error
        panic(err)
    }
}
```
ElasticStore is loaded with a new ElasticClient. I'm able to index documents manually (curl). I run a fresh version of Elastic 2.0, and version 3 of your library. I run golang go1.3.3 linux/amd64. Any idea of what could be wrong? :-)

**Comment by olivere** [comment]
Sorry, only on iPhone now. Any chance you can test with Go 1.5 (or disabling health checks)? http.Client changed in 1.4. Just a guess though...

**Comment by olivere** [comment]
Hey. Can you extract a complete working program. It seems that `AddTweet` gets a `nil` pointer and/or `s.client` is `nil` as well:

```go
gopkg.in/olivere/elastic%2ev3.(*Client).PerformRequest(0x0, 0x811c80, 0x3, 0xc2080009b0, 0x10, 0xc208020f60, 0x7c6000, 0xc208046000, 0x0, 0x0, ...)
    /home/aspic/dev/git/words/server/src/gopkg.in/olivere/elastic.v3/client.go:884 +0xe03
...
store.ElasticStore.AddTweet(0x0)
    /home/aspic/dev/git/words/server/src/store/store.go:90 +0x13f
```

The referenced line with the exception is [line 884](https://github.com/olivere/elastic/blob/release-branch.v3/client.go#L884), which is just a simple access to a Mutex (assuming you are using the most recent version of v3):

```go
c.mu.RLock()
```

I wonder how you initialize `ElasticStore` (e.g. is it a value type for a reason?) and how you create an Elastic client.

Thank you.

**Comment by aspic** [comment]
Thanks for your reply. I tried with an even simpler example (not wrapping the client) and now it works as expected. In other words the error is probably in my code. :-)
