### ISSUE TITLE
error=elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]

### ISSUE THREAD

**Issue by guoxijun** [olivere/elastic#525]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v5 (for Elasticsearch 5.x)

my code:
timeline := elastic.NewTermsAggregation().Field("operation").Size(10).OrderByCountDesc()
searchResult, err := m.Client.Search().          
    Index(indexName).
    Query(elastic.NewMatchAllQuery()).
    Aggregation("timeline", timeline).
    Pretty(true).
    Do(context.Background())

my es settings:
"operation" : {
  "type" : "text",
  "fields" : {
    "keyword" : {
      "type" : "keyword",
      "ignore_above" : 256
    }
  }
},

why i always get the error:
error=elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]

and if i use SearchType("count"),it will print the err:
error=elastic: Error 400 (Bad Request): No search type for [count] [type=illegal_argument_exception

please help me

**Comment by olivere** [comment]
The error is probably because you are trying to do a term query on a `text` field. Use e.g. a `keyword` field to do a [term query](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/query-dsl-term-query.html). See [the introduction of `text` and `keyword` as a breaking change in 5.0](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/breaking_50_mapping_changes.html#_literal_string_literal_fields_replaced_by_literal_text_literal_literal_keyword_literal_fields), and the documentation for [`text`](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/text.html) and [`keyword`](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/keyword.html).

Please consult an introduction into Elasticsearch and how it deals with human language. [The Definite Guide](https://www.elastic.co/guide/en/elasticsearch/guide/master/index.html) is a bit outdated, but a wonderful introduction.

The `search_type=count` [has been removed in 5.0](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/breaking_50_search_changes.html#_literal_search_type_count_literal_removed).

**Comment by nvma** [comment]
Hello, @olivere. Thank you for the rich client.
I experience similar error by running an example code from Getting Started section on github.io site. It does get an entry by id, but fails on executing search by query `termQuery := elastic.NewTermQuery("user.keyword", "olivere")`.  Maybe there's something wrong with my ES setup?
```
playground ➜ go run main.go 
Elasticsearch returned with code 200 and version 5.5.0
Elasticsearch version 5.5.0
Indexed tweet 1 to index twitter, type tweet
Indexed tweet 2 to index twitter, type tweet
Got document 1 in version 842351863608 from index twitter, type tweet
panic: elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]

goroutine 1 [running]:
panic(0x669560, 0xc4201568e0)
	/home/nvma/.gvm/gos/go1.7.3/src/runtime/panic.go:500 +0x1a1
main.main()
	/home/nvma/work/go/src/github.com/nvma/playground/main.go:132 +0x1eb7
exit status 2
```

**Comment by olivere** [comment]
@nvma I just ran the code on the Elastic website. No problems.

```
$ go run example.go
Elasticsearch returned with code 200 and version 5.5.0
Elasticsearch version 5.5.0Indexed tweet 1 to index twitter, type tweet
Indexed tweet 2 to index twitter, type tweet
Got document 1 in version 842351749720 from index twitter, type tweet
Query took 47 milliseconds
Tweet by olivere: It's a Raggy Waltz
Tweet by olivere: Take Five
Found a total of 2 tweets
Found a total of 2 tweets
Tweet by olivere: It's a Raggy Waltz
Tweet by olivere: Take Five
New version of tweet "1" is now 2
```

Can you post the code, please.

**Comment by olivere** [comment]
@nvma Please look into the Elasticsearch log file for details about the error (or, even better, [enable the trace log](https://github.com/olivere/elastic/wiki/Logging)), and post the output here.

**Comment by nvma** [comment]
@olivere thank your for the fast reponse! The code I ran was copied verbatim from the website:
```
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"reflect"
	"time"

	"golang.org/x/net/context"

	elastic "gopkg.in/olivere/elastic.v5"
)

// Tweet is a structure used for serializing/deserializing data in Elasticsearch.
type Tweet struct {
	User     string                `json:"user"`
	Message  string                `json:"message"`
	Retweets int                   `json:"retweets"`
	Image    string                `json:"image,omitempty"`
	Created  time.Time             `json:"created,omitempty"`
	Tags     []string              `json:"tags,omitempty"`
	Location string                `json:"location,omitempty"`
	Suggest  *elastic.SuggestField `json:"suggest_field,omitempty"`
}

func main() {
	// Starting with elastic.v5, you must pass a context to execute each service
	ctx := context.Background()

	// Obtain a client and connect to the default Elasticsearch installation
	// on 127.0.0.1:9200. Of course you can configure your client to connect
	// to other hosts and configure it in various other ways.
	client, err := elastic.NewClient(
		elastic.SetTraceLog(log.New(os.Stderr, "[[TRACE LOG]] ", 0)))
	if err != nil {
		// Handle error
		panic(err)
	}

        ...

	if !deleteIndex.Acknowledged {
		// Not acknowledged
	}
}
```

Here's the complete log just in case.

```
playground ➜ grm
Elasticsearch returned with code 200 and version 5.5.0
Elasticsearch version 5.5.0
[[TRACE LOG]] HEAD /twitter HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.6 (linux-amd64)
Accept: application/json


[[TRACE LOG]] HTTP/1.1 200 OK
Content-Length: 676
Content-Type: application/json; charset=UTF-8


[[TRACE LOG]] PUT /twitter/tweet/1 HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.6 (linux-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

1
{
55
"user":"olivere","message":"Take Five","retweets":0,"created":"0001-01-01T00:00:00Z"}
0


[[TRACE LOG]] HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

8f
{"_index":"twitter","_type":"tweet","_id":"1","_version":11,"result":"updated","_shards":{"total":1,"successful":1,"failed":0},"created":false}
0


Indexed tweet 1 to index twitter, type tweet
[[TRACE LOG]] PUT /twitter/tweet/2 HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.6 (linux-amd64)
Content-Length: 54
Accept: application/json
Accept-Encoding: gzip

{"user" : "olivere", "message" : "It's a Raggy Waltz"}
[[TRACE LOG]] HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8
Warning: 299 Elasticsearch-5.5.0-260387d "Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header." "Fri, 21 Jul 2017 11:45:12 GMT"

8f
{"_index":"twitter","_type":"tweet","_id":"2","_version":10,"result":"updated","_shards":{"total":1,"successful":1,"failed":0},"created":false}
0


Indexed tweet 2 to index twitter, type tweet
[[TRACE LOG]] GET /twitter/tweet/1 HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.6 (linux-amd64)
Accept: application/json
Accept-Encoding: gzip


[[TRACE LOG]] HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

aa
{"_index":"twitter","_type":"tweet","_id":"1","_version":11,"found":true,"_source":{"user":"olivere","message":"Take Five","retweets":0,"created":"0001-01-01T00:00:00Z"}}
0


Got document 1 in version 842352804032 from index twitter, type tweet
[[TRACE LOG]] POST /twitter/_flush HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.6 (linux-amd64)
Content-Length: 0
Accept: application/json
Accept-Encoding: gzip


[[TRACE LOG]] HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

31
{"_shards":{"total":1,"successful":1,"failed":0}}
0


[[TRACE LOG]] POST /twitter/_search?pretty=true HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.6 (linux-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

1
{
69
"from":0,"query":{"term":{"user.keyword":"olivere"}},"size":10,"sort":[{"user.keyword":{"order":"asc"}}]}
0


panic: elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]

goroutine 1 [running]:
panic(0x669680, 0xc42023c360)
	/home/nvma/.gvm/gos/go1.7.3/src/runtime/panic.go:500 +0x1a1
main.main()
	/home/nvma/work/go/src/github.com/nvma/playground/main.go:136 +0x1f8b
exit status 2
```

**Comment by olivere** [comment]
That's very strange. You're using 5.0.6 which is rather old. Can you please update to the recent version by doing `go get -u gopkg.in/olivere/elastic.v5`, then try again? That should also include the HTTP response in the failure case in the trace log.

**Comment by nvma** [comment]
Updated to `5.0.43`  and the trace log is more detailed.

```
Elasticsearch returned with code 200 and version 5.5.0
Elasticsearch version 5.5.0
[[TRACE LOG]] HEAD /twitter HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.43 (linux-amd64)
Accept: application/json
Content-Type: application/json


[[TRACE LOG]] HTTP/1.1 200 OK
Content-Length: 676
Content-Type: application/json; charset=UTF-8


[[TRACE LOG]] PUT /twitter/tweet/1 HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.43 (linux-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

1
{
55
"user":"olivere","message":"Take Five","retweets":0,"created":"0001-01-01T00:00:00Z"}
0


[[TRACE LOG]] HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

8f
{"_index":"twitter","_type":"tweet","_id":"1","_version":14,"result":"updated","_shards":{"total":1,"successful":1,"failed":0},"created":false}
0


Indexed tweet 1 to index twitter, type tweet
[[TRACE LOG]] PUT /twitter/tweet/2 HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.43 (linux-amd64)
Content-Length: 54
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

{"user" : "olivere", "message" : "It's a Raggy Waltz"}
[[TRACE LOG]] HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

8f
{"_index":"twitter","_type":"tweet","_id":"2","_version":13,"result":"updated","_shards":{"total":1,"successful":1,"failed":0},"created":false}
0


Indexed tweet 2 to index twitter, type tweet
[[TRACE LOG]] GET /twitter/tweet/1 HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.43 (linux-amd64)
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip


[[TRACE LOG]] HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

aa
{"_index":"twitter","_type":"tweet","_id":"1","_version":14,"found":true,"_source":{"user":"olivere","message":"Take Five","retweets":0,"created":"0001-01-01T00:00:00Z"}}
0


Got document 1 in version 842351380128 from index twitter, type tweet
[[TRACE LOG]] POST /twitter/_flush HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.43 (linux-amd64)
Content-Length: 0
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip


[[TRACE LOG]] HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

31
{"_shards":{"total":1,"successful":1,"failed":0}}
0


[[TRACE LOG]] POST /twitter/_search?pretty=true HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.43 (linux-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

1
{
69
"from":0,"query":{"term":{"user.keyword":"olivere"}},"size":10,"sort":[{"user.keyword":{"order":"asc"}}]}
0


[[TRACE LOG]] HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

312
{
  "error" : {
    "root_cause" : [
      {
        "type" : "query_shard_exception",
        "reason" : "No mapping found for [user.keyword] in order to sort on",
        "index_uuid" : "rHgCvsOETQeo3jlV5fzQ6Q",
        "index" : "twitter"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "twitter",
        "node" : "0pAenCAYSkyDJkhM7__aTA",
        "reason" : {
          "type" : "query_shard_exception",
          "reason" : "No mapping found for [user.keyword] in order to sort on",
          "index_uuid" : "rHgCvsOETQeo3jlV5fzQ6Q",
          "index" : "twitter"
        }
      }
    ]
  },
  "status" : 400
}

0


searchResult err: elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x402062]
``

**Comment by nvma** [comment]
Following the trace log I've commented out `Sort("user.keyword", true)` and no error this time. I remember when I was using v3 I was doing something like `client.CreateIndex("idx").Body(mapping).Do(ctx)` passing mapping,  mocking JSON in a multiline string.

**Comment by olivere** [comment]
Yes. There needs to be a mapping. Still figuring out why it works here and doesn't work for you.

The reason for this problem is that once you index the first tweet, the `user` should be of type `string`. In 5.4, `string` is just an alias for a `text` field which is multi-mapped with a `keyword` field. So while you cannot sort on a `text` field, you can use `<field>.keyword` for string fields, according to [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/breaking_50_mapping_changes.html#_literal_string_literal_fields_replaced_by_literal_text_literal_literal_keyword_literal_fields).

Anyway... a proper mapping should do the job. I'm adding it.

**Comment by olivere** [comment]
@nvma Does [this](https://gist.github.com/olivere/50ad8bbb4e9440d4b004f5d82fc6d58c) work for you?

**Comment by nvma** [comment]
@olivere works like a charm! Now following your mappings I can start building mappings for my data, that was the hardest part for me. Thanks, you rock!
