### ISSUE TITLE
Nullpointer BulkProcessor PerformRequest

### ISSUE THREAD

**Issue by jrots** [olivere/elastic#592]
Im trying to use the BulkProcessor but I get a segfault each time it wants to execute it's requests..
it can't find the client, seems like the client doesn't exist anymore somehow? 
Any idea how this can happen? 
(added the fmt.Println stuff manually)

```	
c, _ = elastic.NewClient(
		elastic.SetURL("elastic01:9200"))	
bulk, err := c.BulkProcessor().Name("MyBackgroundWorker-1").
		Workers(2).
		BulkActions(1000).               // commit if # requests >= 1000
		BulkSize(2 << 20).               // commit if size of requests >= 2 MB
		FlushInterval(30 * time.Second). // commit every 30s
		Do(context.Background())
```

```
func (c *Client) PerformRequest(ctx context.Context, method, path string, params url.Values, body interface{}, ignoreErrors ...int) (*Response, error) {
	start := time.Now().UTC()

	fmt.Println("aaaa")
	fmt.Println(c.mu)
	c.mu.RLock()
```
```
aaaa
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x129db83]

goroutine 34 [running]:
github.com/jrots/go-mysql-elasticsearch/vendor/gopkg.in/olivere/elastic%2ev6.(*Client).PerformRequest(0x0, 0x15173c0, 0xc420078370, 0x1391c10, 0x4, 0xc4223f6000, 0x6, 0xc421357be8, 0x1311d40, 0xc4223f6010, ...)
	/Users/jayme/Documents/projects/go/src/github.com/jrots/go-mysql-elasticsearch/vendor/gopkg.in/olivere/elastic.v6/client.go:1182 +0x143
github.com/jrots/go-mysql-elasticsearch/vendor/gopkg.in/olivere/elastic%2ev6.(*BulkService).Do(0xc420184000, 0x15173c0, 0xc420078370, 0xc421a38000, 0x0, 0xc42002d5d0)
	/Users/jayme/Documents/projects/go/src/github.com/jrots/go-mysql-elasticsearch/vendor/gopkg.in/olivere/elastic.v6/bulk.go:237 +0x3af
github.com/jrots/go-mysql-elasticsearch/vendor/gopkg.in/olivere/elastic%2ev6.(*bulkWorker).commit.func1(0x2, 0x2)
	/Users/jayme/Documents/projects/go/src/github.com/jrots/go-mysql-elasticsearch/vendor/gopkg.in/olivere/elastic.v6/bulk_processor.go:471 +0x4d
github.com/jrots/go-mysql-elasticsearch/vendor/gopkg.in/olivere/elastic%2ev6.RetryNotify(0xc42249e000, 0x1512000, 0xc421a38000, 0xc421357eb8, 0x2, 0x0)
	/Users/jayme/Documents/projects/go/src/github.com/jrots/go-mysql-elasticsearch/vendor/gopkg.in/olivere/elastic.v6/retry.go:40 +0x32
github.com/jrots/go-mysql-elasticsearch/vendor/gopkg.in/olivere/elastic%2ev6.(*bulkWorker).commit(0xc420152280, 0x15173c0, 0xc420078370, 0x1, 0xc420184000)
	/Users/jayme/Documents/projects/go/src/github.com/jrots/go-mysql-elasticsearch/vendor/gopkg.in/olivere/elastic.v6/bulk_processor.go:498 +0x29d
github.com/jrots/go-mysql-elasticsearch/vendor/gopkg.in/olivere/elastic%2ev6.(*bulkWorker).work(0xc420152280, 0x15173c0, 0xc420078370)
	/Users/jayme/Documents/projects/go/src/github.com/jrots/go-mysql-elasticsearch/vendor/gopkg.in/olivere/elastic.v6/bulk_processor.go:442 +0x22e
created by github.com/jrots/go-mysql-elasticsearch/vendor/gopkg.in/olivere/elastic%2ev6.(*BulkProcessor).Start
	/Users/jayme/Documents/projects/go/src/github.com/jrots/go-mysql-elasticsearch/vendor/gopkg.in/olivere/elastic.v6/bulk_processor.go:299 +0x32c
exit status 2
```

**Comment by jrots** [comment]
nvm my bad.. I didnt check the error state when creating the client :$ 
```panic: health check timeout: no Elasticsearch node available```
explains my problem ;)
