### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by wangxiangyu** [olivere/elastic#692]
I am using elastic.v5 and go 1.9
I use bulk processor to index log to elasticsearch and BulkProcessor is configured as follows:
```
	p, err := b.c.BulkProcessor().
		Workers(20). // # of workers
		BulkActions(5000). // # of queued requests before committed
		BulkSize(10240000). // # of bytes in requests before committed
		FlushInterval(10 * time.Second). // autocommit every 10 seconds
		Stats(true). // gather statistics
		Do(ctx)
```
 After started, The following error occurred:
```
fatal error: concurrent map iteration and map write

goroutine 346 [running]:
runtime.throw(0x929adb, 0x26)
        /usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc420370958 sp=0xc420370938 pc=0x42d1f5
runtime.mapiternext(0xc4218c0540)
        /usr/local/go/src/runtime/hashmap.go:778 +0x6f1 fp=0xc4203709f0 sp=0xc420370958 pc=0x40b461
runtime.mapiterinit(0x87f600, 0xc4277189f0, 0xc4218c0540)
        /usr/local/go/src/runtime/hashmap.go:768 +0x270 fp=0xc420370a58 sp=0xc4203709f0 pc=0x40ab10
reflect.mapiterinit(0x87f600, 0xc4277189f0, 0x15)
        /usr/local/go/src/runtime/hashmap.go:1240 +0x54 fp=0xc420370a88 sp=0xc420370a58 pc=0x40c744
reflect.Value.MapKeys(0x87f600, 0xc4277189f0, 0x15, 0x0, 0x409bd9, 0xc420370c20)
        /usr/local/go/src/reflect/value.go:1098 +0xcc fp=0xc420370b38 sp=0xc420370a88 pc=0x4b1c8c
encoding/json.(*mapEncoder).encode(0xc420244060, 0xc426b384d0, 0x87f600, 0xc4277189f0, 0x15, 0x870100)
        /usr/local/go/src/encoding/json/encode.go:666 +0xad fp=0xc420370ca8 sp=0xc420370b38 pc=0x516f4d
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc426b384d0, 0x87f600, 0xc4277189f0, 0x15, 0xc427710100)
        /usr/local/go/src/encoding/json/encode.go:698 +0x64 fp=0xc420370ce8 sp=0xc420370ca8 pc=0x5218a4
encoding/json.(*encodeState).reflectValue(0xc426b384d0, 0x87f600, 0xc4277189f0, 0x15, 0x100)
        /usr/local/go/src/encoding/json/encode.go:323 +0x82 fp=0xc420370d20 sp=0xc420370ce8 pc=0x514842
encoding/json.(*encodeState).marshal(0xc426b384d0, 0x87f600, 0xc4277189f0, 0xc4288a0100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:296 +0xaf fp=0xc420370d58 sp=0xc420370d20 pc=0x51452f
encoding/json.Marshal(0x87f600, 0xc4277189f0, 0x40, 0x40, 0xc4288a00c0, 0x40, 0x0)
        /usr/local/go/src/encoding/json/encode.go:161 +0x5f fp=0xc420370da0 sp=0xc420370d58 pc=0x5141af
billions-index-slb/vendor/gopkg.in/olivere/elastic%2ev5.(*BulkIndexRequest).Source(0xc427762a80, 0x2, 0x2, 0xc420370fb0, 0x2, 0x2)
        /root/golib/src/billions-index-slb/vendor/gopkg.in/olivere/elastic.v5/bulk_index_request.go:205 +0x3d4 fp=0xc420370e28 sp=0xc420370da0 pc=0x6999c4
billions-index-slb/vendor/gopkg.in/olivere/elastic%2ev5.(*BulkService).estimateSizeInBytes(0xc420266630, 0xbadae0, 0xc427762a80, 0x6d6)
        /root/golib/src/billions-index-slb/vendor/gopkg.in/olivere/elastic.v5/bulk.go:146 +0x31 fp=0xc420370e68 sp=0xc420370e28 pc=0x696ea1
billions-index-slb/vendor/gopkg.in/olivere/elastic%2ev5.(*BulkService).EstimatedSizeInBytes(0xc420266630, 0xc420370f18)
        /root/golib/src/billions-index-slb/vendor/gopkg.in/olivere/elastic.v5/bulk.go:136 +0x98 fp=0xc420370eb8 sp=0xc420370e68 pc=0x696de8
billions-index-slb/vendor/gopkg.in/olivere/elastic%2ev5.(*bulkWorker).commitRequired(0xc4203c78c0, 0xc420370f18)
        /root/golib/src/billions-index-slb/vendor/gopkg.in/olivere/elastic.v5/bulk_processor.go:541 +0x5d fp=0xc420370ed8 sp=0xc420370eb8 pc=0x69c28d
billions-index-slb/vendor/gopkg.in/olivere/elastic%2ev5.(*bulkWorker).work(0xc4203c78c0, 0xbb03e0, 0xc420018028)
        /root/golib/src/billions-index-slb/vendor/gopkg.in/olivere/elastic.v5/bulk_processor.go:441 +0x206 fp=0xc420370fc8 sp=0xc420370ed8 pc=0x69b986
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420370fd0 sp=0xc420370fc8 pc=0x45b8f1
created by billions-index-slb/vendor/gopkg.in/olivere/elastic%2ev5.(*BulkProcessor).Start
        /root/golib/src/billions-index-slb/vendor/gopkg.in/olivere/elastic.v5/bulk_processor.go:299 +0x1ba
```
Any idea??

**Comment by olivere** [comment]
Wow, that's strange. It's happening [here](https://github.com/olivere/elastic/blob/release-branch.v5/bulk_index_request.go#L205), and states that two concurrent goroutines are trying to update the same underlying dictionary:

```
command := bulkIndexRequestCommand{
	r.opType: indexCommand,
}
```

I wonder how that might be the case, as `command` is a local variable...

Can you post a snippet that panics reproducibly?

**Comment by olivere** [comment]
The error is [described here](https://beta.golang.org/doc/go1.8#mapiter). Can you run your program with the [race detector](https://blog.golang.org/race-detector) enabled? Maybe that can give us a hint.

**Comment by wangxiangyu** [comment]
@olivere ok, I will try to run race detector.

**Comment by wangxiangyu** [comment]
@olivere I ran `race detector` and found a bug  which I made.  `A map was accessed by multi go routine concurrently.`  Thank you so much!

**Comment by olivere** [comment]
@avantassel Did you already run your programm with race detector enabled?

**Comment by avantassel** [comment]
Sorry I posted in the wrong repo, the issue was fixed recently, https://github.com/elastic/beats/pull/8238

**Comment by thangld322** [comment]
```

fatal error: concurrent map read and map write

goroutine 22 [running]:

runtime.throw(0xf519bd, 0x21)

                /usr/lib/go-1.10/src/runtime/panic.go:616 +0x81
fp=0xc42028f5a0 sp=0xc42028f580 pc=0x47e231

runtime.mapaccess2(0xe96960, 0xc4201fc180, 0xc420354de0, 0xc420354d01,
0x100000000000098)

                /usr/lib/go-1.10/src/runtime/hashmap.go:409 +0x2cf
fp=0xc42028f610 sp=0xc42028f5a0 pc=0x45809f

reflect.mapaccess(0xe96960, 0xc4201fc180, 0xc420354de0, 0xc4201fc180)

                /usr/lib/go-1.10/src/runtime/hashmap.go:1195 +0x3f
fp=0xc42028f648 sp=0xc42028f610 pc=0x45aa1f

reflect.Value.MapIndex(0xe96960, 0xc4201cc058, 0x195, 0xe42ec0,
0xc420354de0, 0x98, 0x0, 0x0, 0x0)

                /usr/lib/go-1.10/src/reflect/value.go:1081 +0x17c
fp=0xc42028f740 sp=0xc42028f648 pc=0x5312cc

encoding/json.(*mapEncoder).encode(0xc4201be038, 0xc420234210, 0xe96960,
0xc4201cc058, 0x195, 0x100)

                /usr/lib/go-1.10/src/encoding/json/encode.go:684 +0x6d2
fp=0xc42028f950 sp=0xc42028f740 pc=0x588c02

encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc420234210,
0xe96960, 0xc4201cc058, 0x195, 0xc4201c0100)

                /usr/lib/go-1.10/src/encoding/json/encode.go:700 +0x61
fp=0xc42028f998 sp=0xc42028f950 pc=0x597231

encoding/json.(*ptrEncoder).encode(0xc4201be040, 0xc420234210, 0xe766e0,
0xc4201cc058, 0x16, 0xf90100)

                /usr/lib/go-1.10/src/encoding/json/encode.go:780 +0x10c
fp=0xc42028f9f8 sp=0xc42028f998 pc=0x58997c

encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc420234210,
0xe766e0, 0xc4201cc058, 0x16, 0xc4201c0100)

                /usr/lib/go-1.10/src/encoding/json/encode.go:785 +0x61
fp=0xc42028fa40 sp=0xc42028f9f8 pc=0x5973b1

encoding/json.(*encodeState).reflectValue(0xc420234210, 0xe766e0,
0xc4201cc058, 0x16, 0x100)

                /usr/lib/go-1.10/src/encoding/json/encode.go:325 +0x7f
fp=0xc42028fa80 sp=0xc42028fa40 pc=0x5850ff

encoding/json.(*encodeState).marshal(0xc420234210, 0xe766e0, 0xc4201cc058,
0x100, 0x0, 0x0)

                /usr/lib/go-1.10/src/encoding/json/encode.go:298 +0xc1
fp=0xc42028fad0 sp=0xc42028fa80 pc=0x584d21

encoding/json.Marshal(0xe766e0, 0xc4201cc058, 0x0, 0x0, 0x0, 0x0, 0x0)

                /usr/lib/go-1.10/src/encoding/json/encode.go:161 +0xdc
fp=0xc42028fb50 sp=0xc42028fad0 pc=0x5845fc

github.com/olivere/elastic.(*BulkIndexRequest).Source(0xc4200ad110, 0x0,
0x0, 0x0, 0x0, 0x0)


/home/thangld/go/src/github.com/olivere/elastic/bulk_index_request.go:220
+0x7b8 fp=0xc42028fe00 sp=0xc42028fb50 pc=0x9b7808

github.com/olivere/elastic.(*bulkWorker).work(0xc4200bad80, 0xf9a6c0,
0xc4200b2010)


/home/thangld/go/src/github.com/olivere/elastic/bulk_processor.go:484 +0x1e6
fp=0xc42028ffc8 sp=0xc42028fe00 pc=0x9bc086

runtime.goexit()

                /usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1
fp=0xc42028ffd0 sp=0xc42028ffc8 pc=0x4ac101

created by github.com/olivere/elastic.(*BulkProcessor).Start


/home/thangld/go/src/github.com/olivere/elastic/bulk_processor.go:336 +0x36d

```

My code was running fine then today it occurred this error too. :( 

Please help...
