### ISSUE TITLE
panic occurs in concurrent client search

### ISSUE THREAD

**Issue by lijasonvip** [olivere/elastic#982]
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
elastic.Client do search job concurrently, just search success or search fail.

### Please describe the actual behavior
panic occurs.

```
panic: runtime error: invalid memory address or nil pointer dereference
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x63cbc6]

goroutine 3427064 [running]:
github.com/olivere/elastic.(*Client).Stop(0x0)
    /home/richardlili/go/src/github.com/olivere/elastic/client.go:774 +0x26
panic(0x6a4dc0, 0x8832c0)
    /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/olivere/elastic.(*Client).PerformRequest(0x0, 0x73ae80, 0xc4200140a0, 0x701b22, 0x4, 0xc431d90ce0, 0x13, 0xc448a25680, 0x67fa80, 0xc43efa26e0, ...)
    /home/richardlili/go/src/github.com/olivere/elastic/client.go:1253 +0xd6
github.com/olivere/elastic.(*IndicesAnalyzeService).Do(0xc454e11d90, 0x73ae80, 0xc4200140a0, 0x1, 0xc454e11d90, 0x0)
    /home/richardlili/go/src/github.com/olivere/elastic/indices_analyze.go:192 +0x149
main.doSearch(0xc4366d4914, 0xc, 0x0)
    /home/richardlili/go/src/benchElastic/bench.go:79 +0x460
main.main.func1(0xc4407d0000, 0x69a197, 0x7e5800, 0xc42ff7a000)
    /home/richardlili/go/src/benchElastic/bench.go:48 +0x63
created by main.main
    /home/richardlili/go/src/benchElastic/bench.go:46 +0x307
```

### Any steps to reproduce the behavior?
reproduce every time.

my code:
```
for i:=0; i<querycount; i++ {
		worker <- 1
		go func() {
			index := rand.Intn(len(querys)-1)
			doSearch(querys[index], 0)
			<-worker
		}()
}


func doSearch(){
   client, err := elastic.NewClient(xxxxxx)
   defer client.Stop()
   ctx := context.Background()
    //some bool query composed

  //search and sort
}

```

**Comment by olivere** [comment]
Two comments here. First, please make sure to catch errors before using `client`. The `client.Stop()` might just cause your problem because `client` is `nil` because there was an error in `elastic.NewClient(...)`. Second, you shouldn't create a new client for each search. Instead, you should be creating a single `client` and pass that to `doSearch` instead.
